"""add post likes

Revision ID: 443f8b095aa1
Revises: 51e6802985b0
Create Date: 2026-05-02 22:13:04.135211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443f8b095aa1'
down_revision = '51e6802985b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_likes')
    # ### end Alembic commands ###
